### ISSUE TITLE
Tracking file Packaging/debian/control

### ISSUE THREAD

**Issue by mmiladi** [s-will/LocARNA#1]
The configure/make process modifies the file 'Packaging/debian/control'
This generates a conflict error complain whenever a pull is invoked.
Error message:
`error: Your local changes to the following files would be overwritten by checkout:
    Packaging/debian/control
Please, commit your changes or stash them before you can switch branches.
Aborting
`

**Comment by s-will** [comment]
This is resolved by deleting the link.
