### ISSUE TITLE
free_end_gaps parameter description ambiguous

### ISSUE THREAD

**Issue by TorHou** [s-will/LocARNA#11]
Hello Sebastian,
i just wanted to let you know that I had to look in the source code to understand the format of the free_end_gaps parameter. I thought the "-" minus signs are just placeholder and tried to do things like: "R1L1" or "TTFF" to specify which end gaps I want to be free. The help could use a small update on this.

**Comment by s-will** [comment]
@TorHou, this is improved now (intelligible?); at this opportunity, I also improved general help output to prepare for longer, more verbose help text
