### ISSUE TITLE
Cannot find  pkgconfig file RNAlib2.pc

### ISSUE THREAD

**Issue by noncodo** [s-will/LocARNA#16]
While running `./configure --with-vrna=/path/to/ViennaRNA-2.2.10` I get : 

[...]

> configure: error: =======================================================
>  Cannot find  pkgconfig file RNAlib2.pc for the Vienna RNA package (>= 2.3.1)
>  in \'/path/to/ViennaRNA-2.2.10/lib/pkgconfig\'.
>  LocARNA REQUIRES the Vienna RNA package (>= 2.3.1);
>  It is freely available at http://www.tbi.univie.ac.at/RNA/.

yet  `find /path/to/ViennaRNA-2.2.10 -name "RNAlib2.pc"` gives 

> /path/to/ViennaRNA-2.2.10/lib/pkgconfig/RNAlib2.pc

I also tried with `export PKG_CONFIG_PATH=/path/to/ViennaRNA-2.2.10/lib/pkgconfig/`
but this didn't help. Ideas? I am using locarna-1.9.1.tar.gz  from http://www.bioinf.uni-freiburg.de/Software/LocARNA/

**Comment by noncodo** [comment]
Ahh, ignored the >= 2.3.1

**Comment by s-will** [comment]
Hi, thanks for self-solving the issue:).
Be sure to use 2.3.3; not 2.3.2, which has some problem.
