### ISSUE TITLE
--noLP and --free-endgaps option results in segfault in specific scenario

### ISSUE THREAD

**Issue by SchwarzMarek** [s-will/LocARNA#23]
Hello, 

There appears to be some situlation specific bug in locarna 1.9.1.

Originally, I've come across it when I was running mlocarna with --free-endgaps parameter for 5 anchored sequences, which resulted in segfault. The situation did not happen when --free-endgaps were not set in mlocarna because the constructed guide tree was different.

After some digging, I've found that in actually the --noLP flag for locarna aligner together with --free-endgaps are responsible for segfault, when the mlocarna runs the progressive alignment. (The --noLP is set automatically by mlocarna for some reason.)

To recreate the bug I'm attaching a mlocarna output dir. The command in question as reported by --moreverbose is:
`/usr/local/bin/locarna intermediates/intermediate1.pp intermediates/intermediate2.pp --free-endgaps="++++" --struct-weight 200 --max-diff-am 30 --noLP --min-prob 0.0005 --clustal=intermediates/intermediate3.aln --pp=intermediates/intermediate3.pp > /dev/null`

The --noLP together with --free-endgaps result in segfault, others may be set to default.
So the minimal code is `locarna --noLP --free-endgaps ++++ intermediate1.pp intermediate2.pp` from the intermediates dir.

I've traced that the segfault is raised from aligner file, from:
`AlignerImpl::trace_arcmatch_noLP` method, more specifically:
`alignment_.add_basepairA(arcAI.left(),arcAI.right());`

line (1111 in master, 1028 in locarna-1.9.1).

I've tried to build Locarna from git, but did not succeed, so I can't provide any inside for more recent version of Locarna then 1.9.1.

[file1.out.zip](https://github.com/s-will/LocARNA/files/1014373/file1.out.zip)
I hope it helps with tracing the bug.

Best regards
Marek Schwarz

**Comment by s-will** [comment]
Thanks, this is great help! 

To answer one of your questions: --noLP is usually very useful to improve results and slightly speed up the alignment computation.
Compiling from the trunk requires running autoreconf -i first, which sets up autotools, before one can run the usual configure;make;make install sequence.

Unfortunately, the problem persists in the current trunk---at least I have a pretty good idea what goes wrong there...

**Comment by s-will** [comment]
Dear @SchwarzMarek, I found some time to fix this. As of yet, the fix is only in the repository (master branch); please see my last comment on how to compile from the repository. Actually, this bug was related to a deeper problem with the semantics of anchor constraints, which required some larger changes of LocARNA's constraint module.
