### ISSUE TITLE
installing to 'lib/perl' not working in bioconda ..

### ISSUE THREAD

**Issue by martin-raden** [s-will/LocARNA#34]
Hi Sebastian,
installing the MLocarna.pl to `lib/perl` via

https://github.com/s-will/LocARNA/blob/fe6d478e8c4b2a982ccde8a83b7fbbc07c951249/lib/perl/Makefile.am#L3

makes it invisible in bioconda packaging, since conda currently only activates the following pathes in `@INC`:
```[bash]
$(prefix)/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi 
$(prefix)/lib/perl5/site_perl/5.22.0 
$(prefix)/lib/perl5/5.22.0/x86_64-linux-thread-multi 
$(prefix)/lib/perl5/5.22.0
```
could you please either change the installation directory or the bioconda package recipe to get it installed into one of the `@INC` folders?

Thanks,
Martin

**Comment by martin-raden** [comment]
maybe best to setup the `perllibdir` path via configure using `perl -V:sitelib`

something similar was done [here](https://github.com/asterisk/dahdi-tools/blob/754d981621557bae4a48e3a7d641ef86f1dffd41/configure.ac#L112)

with this setup you have to take care whether you set a non-default `prefix` or not (as in the referenced installation from above) and to fallback to `$(prefix)/lib/perl5` if a prefix is explicitely set.

**Comment by martin-raden** [comment]
I did a workaround by explicitely adding `-I CONDALOCARNABINDIR/../lib/perl` to the call of the problematic perl script..

**Comment by mmiladi** [comment]
How about linking $(prefix)/lib/perl content into $(prefix)/lib/perl5/, within bioconda recipe?

**Comment by martin-raden** [comment]
@mmiladi not working neither, see the paths available within `@INC`

**Comment by s-will** [comment]
This should be a problem (only) if you want to include the MLocarna module in one of your own scripts, right? (Or does it occur also for one of the scripts coming with locarna?) Currently, I consider the MLocarna modules kind of private for the locarna scripts (and also version specific), so I decided not to install them automatically in the perl lib path (not only for bioconda install but also for the installation via make install).

We could change this for bioconda; Milad's suggestion would work (if we instead link into one of the search path dirs). This could be easily done in the bioconda recipe.

**Comment by s-will** [comment]
What do you think of this solution? I need to update the locarna bioconda package anyway and could include this.

**Comment by martin-raden** [comment]
@s-will jup, I have to include the MLocarna module in a postprocessing script in the locarna webserver.. only for this the problem occurs.

**Comment by martin-raden** [comment]
but why 'hacking' around in the bioconda script when you could do via configure once and for all?

since I found a solution for my problem, you could keep the module private if you want to. As soon as you want to make it 'public' I would prefer the configure-based solution linked above..

**Comment by martin-raden** [comment]
so up to you whether to close the issue or keep it up until changes towards public PM are made..  😄

**Comment by s-will** [comment]
Moving the modules to the perl search path in general will cause problems when several locarna versions are installed in parallel (at least I do this). In bioconda, one would not have the version problems. Otherwise, if you found a solution already, there is no need to change anything right now, right?

**Comment by martin-raden** [comment]
exactly, as stated above.. ;)

**Comment by s-will** [comment]
very good :)
