### ISSUE TITLE
Calling LocARNA global alignment unsing the --penalize parameter

### ISSUE THREAD

**Issue by teresa-m** [s-will/LocARNA#43]
Hello Sebastian,
we tried to call LocARNA using the penalize parameter, which automatic turns on the local mode. We also tried to enable the local mode explicitly (--sequ-local=False), which was rising an error message. Is there a way to use the penalty for global alignment?
Best,
Teresa

**Comment by s-will** [comment]
done ( v2.0.0RC3, PR #42  )
