### ISSUE TITLE
The Hit line of locarna global alignment sometimes gives wrong positions

### ISSUE THREAD

**Issue by teresa-m** [s-will/LocARNA#44]
Hello Sebastian, 
today I noticed that some LocARNA calls I did generated wrong positions in the HIT line of the output.

one example call I did is:
/some/dir/locarna-1.9.1/bin/mlocarna --tgtdir /some/dir/ --max-diff-am '30' --indel -350 --indel-opening -500 --struct-weight 220 --tau 0 -min-prob '0.005' --write-structure --pw-aligner-options "--pos-output" ../BRALIBASE/k2/U6/U6.apsi-82.sci-68.no-1.raw.fa -moreverbose -v 

and it generated The Hit line:
HIT 9344 1 18446744073709551615 107 101
But the line should look like this:
HIT 9344 1 1 107 101

Best wishes,
Teresa

**Comment by s-will** [comment]
Hi Teresa,

Here is a patch for 1.9.1:
[patch.txt](https://github.com/s-will/LocARNA/files/1958080/patch.txt)
(Apply with patch -p1 <patch.txt). 

Let me know, if you can apply it (otherwise I could provide the tar.gz) and whether
this fixes your problem.

Cheers
Sebastian
