### ISSUE TITLE
Passing --LP gives the error: only one of the options --noLP and --LP can be defined at a time.

### ISSUE THREAD

**Issue by rickbeeloo** [s-will/LocARNA#50]
**FASTA input:**
I have tried numerous FASTAs (with 2 till 1000 sequences) an example is:
```
>test1
AAATCGATCAGCAGCATCAGCTAGCATCAGC
>test2
AGCGTAGCATCGATCGATCGACTAGCTACG
```

**LocARNA version**
LocARNA 1.9.2.1

**Error**
When I simply call:  `mlocarna test.fasta --LP`, it always throws the error: `Only one of the options --noLP and --LP can be defined at a time.` (Notably, passing --noLP works fine)

**Comment by s-will** [comment]
Thank you very much for pointing this out (and sorry for the late response here).
This is fixed in the recent 2.0.0RCx pre-releases
