### ISSUE TITLE
running local - two files.

### ISSUE THREAD

**Issue by Geize** [s-will/LocARNA#67]
Dear, 

Sorry for my silly question.  The software is already installed at the server.. it seems everything is ok. I decided to installed it because I have a thousand sequences to run..Instead, use the webserver. 

  

Calling help from terminal _"... , which
  specify the two input sequences or input alignments"_ 

  

Could you please give some tips to fix it?
Thanks in advance.

**Comment by s-will** [comment]
Note that there are different programs in the LocARNA package. It looks like you are calling locarna, not mlocarna. The former takes two input files, while the latter, mlocarna, takes one fasta file with---typically---multiple RNAs.

**Comment by Geize** [comment]
Hi Sebastian, 
Thanks. Yes, now I realized that. As I said, I have several "groups of RNAs", in the other words,  each one composed by multiple RNAs. It seems in my case should be better run mlocarna. Am I right?

**Comment by s-will** [comment]
[edited: I realized that I mixed up two requests]
Yes, you are right. You definitively want to use mlocarna in most cases---in particular, if you have more than two RNAs. locarna is a more low-level tool, which is used by mlocarna. (Beyond this, the tool locarna can provide some special functionality for direct users).
