### ISSUE TITLE
no structure annotation in stockholm file with 2.0.0RC8

### ISSUE THREAD

**Issue by klamkiew** [s-will/LocARNA#69]
Hi there,

when using `mlocarna --stockholm <INPUT>` with version 2.0.0RC8, the final stockholm alignment does not have the `#=GC SS_cons` annotation. I did the same command with version 1.9.2.1 and 1.9.2.3, and in both cases the annotation line was present. 

For 2.0.0RC8, I have to explicitly call `mlocarna --stockholm --consensus-structure alifold <INPUT>` in order to get the same behavior. I was not able to see from the release note / manual, whether this is intended, thus I created this issue. 

Greetings from Jena!
Kevin

**Comment by s-will** [comment]
Thanks for pointing this out. I intentionally deactivated the computation by default, since it can take significant time especially for large alignments. Unfortunately, this info is 'hidden' in the ChangeLog. Indeed, ```--consensus-structure alifold``` gets the annotation back.
