### ISSUE TITLE
locarna --probabilistic fails to read arc scores

### ISSUE THREAD

**Issue by halabikeren** [s-will/LocARNA#73]
Hi dear team,

I am encountering an issue running locarnap on my fasta alignment: the program fails on reading arc scores from its generated files. Upon execution of the same command, the program will fail in the same step every time, but on different lines.

**Additional details:** 
I am using version 1.9.2.3, installed with conda via bioconda.
I am running the program on on an Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz machine 
distribution: CentOS Linux release 7.3.1611
                            

**input:**
Please find attached the input file I used, as well as the arc scores files which the program fails to read.

**commands:** 
cd <input_path_dir>
mlocarna <input_path_dir> --probabilistic -tgtdir .

**error:**
terminate called after throwing an instance of 'LocAR
[reproducing_data.zip](https://github.com/s-will/LocARNA/files/7552630/reproducing_data.zip)
NA::failure'
  what():  Cannot read arc match scores. Invalid line 9: 67 106 83  0.256865
sh: line 1:   624 Aborted                 (core dumped) */locarna input/JQ654586 input/EU627010 --struct-weight 200 --max-diff-am 30 --noLP --mea-alignment --min-prob 0.0005 --pp=intermediates/intermediate1.pp --clustal=intermediates/intermediate1.aln --read-match-probs=_tmp_.bmps --read-arcmatch-probs=_tmp_.amps > /dev/null
Cannot execute */locarna: Inappropriate ioctl for device

Could you please let me know how to fix it?

Thanks!

**Comment by s-will** [comment]
Hi, many thanks for reporting this - this is at least very confusing behavior.

The problem here is that mlocarna does not work on input sequences with gaps. Please remove the gaps from the input and try again.

**Comment by halabikeren** [comment]
Thanks! indeed, removing the gaps worked for me.
