### ISSUE TITLE
Get partition function of input sequences

### ISSUE THREAD

**Issue by mmiladi** [s-will/LocARNA#9]
Hi Sebastian,
For an structure scoring test I need the partition function (or even better the ensemble energy) of input sequences A & B. I was wondering if you already have extracted this information into some variable. The closest thing I could find in the code is min_free_energy_ entity of the class RnaEnsembleImpl.
If it's not already there could you guide how would be best to get and store that value?
Cheers

**Comment by mmiladi** [comment]
Ok i did some progress. Inside code for `RnaEnsembleImpl::compute_McCaskill_matrices()`
The line where the partiton fold is invoked `pf_fold(c_sequence,c_structure);` Viennalib returns the The "Gibbs free energy of the ensemble", I should store the value in a new member like `ensemble_energy_` and later somewhere pass it to RNAdata or Scoring constructor...
What do you think?

**Comment by s-will** [comment]
Right, the partition function is computed (but currently not stored) by RnaEnsemble / RnaEnsembleImpl. Thus, this should be made available (in analogy to min_free_energy()) as a method partition_function() of the RnaEnsemble class.
The scoring class should get access to this via RnaData, which 'knows' RnaEnsemle. But be aware that the ensemble is not computed in all cases, such that the partition function will not always be available! Again, this is analgous to the min_free_energy, where the function returns -infinity to flag that the energy was not computed; partition_function() should return 0, if it was not computed.
You are very wellcome to implement this and create a PR for further discussion.

**Comment by s-will** [comment]
btw, don't forget to pull; there is no pf_fold call anymore (now: vrna_pf of the new api)

**Comment by mmiladi** [comment]
Thanks for the hints. Without your latest code adaptation  linking Vienna.2.2.X made problems for scoring.
